### ISSUE TITLE
[FE / Javascript] declare commonly used constants as const - MAGIC NUMBER

### ISSUE THREAD

**Issue by ryuina** [YoungLeeHan/YoungleehanKorean#100]
https://github.com/YoungLeeHan/YoungleehanKorean/blob/a45be186a1c9aa8ebc7252bde0b215c31f6db9b5/client/src/components/nav/Header.js#L121

I see several `1023`s on many places. 
This Magic Number is better to be declared as named constant.

In this case, you can make a `constants.js` somewhere, and declare the value with a naming describing the value.

```
// constants.js
export const DesktopWidth = 1023;
```

```
// nav.js
{width < DesktopWidth && ...
```

**Comment by sweetrain05** [comment]
Hi Ina,
Thanks for pointing this out! This is a really great idea. :)

I made a separate folder named `constants` and and made a file `constant.js` in it. 
I wasn't sure if I should 
make multiple files for different constants/group of similar constants 
OR 
put them all in one `constant.js` file. 

For now, I took the second option and put them all in one `constant.js` file. 
If it becomes too populated, I will consider dividing them into separate files. (for this, I made a constant folder just in case)

![image](https://github.com/YoungLeeHan/YoungleehanKorean/assets/86023470/4cbd207e-cf10-41b4-aef4-764200497381)
# #
