### ISSUE TITLE
[BE] Nodemailer e-mail verification

### ISSUE THREAD

**Issue by sweetrain05** [YoungLeeHan/YoungleehanKorean#121]
Hi Younghyun, great job on developing e-mail verification process using Nodemailer.
I just got an e-mail to confirm my email address, and it's working!! 👍👍👍
However, I was thinking that we could provide a better customer experience if we could provide them with a hyperlink, instead of just text of link. 

This is the email I received:
![image](https://github.com/YoungLeeHan/YoungleehanKorean/assets/86023470/6378ca10-9edf-451f-93b0-c4ad573bb4ee)

In addition, while I was looking at the BE code, came up with few suggestions as following:
1) Place `http://localhost:3000` in BE `.env`, so that we could replace this easily when we go on to actual production url.
![image](https://github.com/YoungLeeHan/YoungleehanKorean/assets/86023470/9d628a82-83d6-440f-aeaf-705e02fd97be)

2) Since the verification code is repeating on both `login` and `register` controllers in `auth.js`,
why don't we make it into a reusable function? It will be a good choice for code maintenance.

**Comment by younghyunlee22** [comment]
Thank you for your suggestions.
1. When I tested the function, I got it as a hyperlink, so I didn't know about the issue. If there's any chance that it could be sent as plain text, we should fix it. I will assign `http://localhost:3000` to a variable and store it in our `.env` file.
2. I will consolidate those two functions into one and use it inside both the register and login functions.
