### ISSUE TITLE
[Recommend] Apply Eslint, Prettier for standardized coding style

### ISSUE THREAD

**Issue by ryuina** [YoungLeeHan/YoungleehanKorean#50]
## Apply Eslint & Prettier
How about considering using linter and prettier on both BE and FE codes? 
Most of the teams using Eslint and prettier for standardize their codes.
And also we can qualify our codes to professional level by seeing the result from them.

Both configuration Eslint & Prettier are very different from projects to projects because the configuration depends on the tech stacks.

They can help you if you aim for the "good codes" 😀

### References
- https://eslint.org/
- https://prettier.io/
- https://github.com/prettier/eslint-config-prettier

### Comments
- eslint and prettier is a little bit same but different. linter is fixing and preventing problem simply, but prettier is on the "prettier code" side.
- there are a lot of examples for the configurations. so you can just follow one of them because every rules are good enough. It's a matter of preference

**Comment by sweetrain05** [comment]
Hi Ina, Thanks for pointing this out. 
I believe that everyone in the team has applied this, so I will close the issue.
