### ISSUE TITLE
[Git] Don't include IDE environments like .idea , .code

### ISSUE THREAD

**Issue by ryuina** [YoungLeeHan/YoungleehanKorean#51]
## Setting .gitignore to not include .idea & .vscode
Please don't include them. It can affects on others' settings XD
Also, setting files can make unintended conflicts.

### Comments
- you can use any IDEs whatever you want. 
- you can also set IDE with light modes, but many developers don't like them 😇 
  - Darker modes are on trend 😎
- intellij vs vscode : No answer. Many typescript developers says vscode is really good for typescript But also intellij is really affordable

**Comment by sweetrain05** [comment]
In addition to Young's work, I just deleted .idea folder on the main branch. Hopefully it won't appear anymore!
