### ISSUE TITLE
[React] Don't need to be a component if not render

### ISSUE THREAD

**Issue by ryuina** [YoungLeeHan/YoungleehanKorean#58]
https://github.com/YoungLeeHan/YoungleehanKorean/blob/7e913c9bf9db725dcd63306a6c780208b57963ea/client/src/components/nav/ScrollToTop.js#L5-L11

## hook vs component
In this case, you don't need to describe this code as a component. 
"Describing as a component" includes a Capital CamelCase naming, and not start with `use`.
At the first glance, I thought it is as component by its naming but it wasn't.
So this code should have more custom-hook-like looks.

### TO-BE
```js
export default function useScrollToTop() {
    useEffect(() => {
        window.scrollTo(0, 0);
    }, []);
}
```

```js
export default function SingleProductView() {
    useScrollToTop();

    // state
    const [product, setProduct] = useState();
    // ...
```

**Comment by sweetrain05** [comment]
Thanks for the suggestion! 
I see that you have already fixed this on your new commit. 
I will keep this naming rule in mind next time I create a hook. 👍
