### ISSUE TITLE
[FE / Javascript] love namings for boolean starts from is...

### ISSUE THREAD

**Issue by ryuina** [YoungLeeHan/YoungleehanKorean#98]
https://github.com/YoungLeeHan/YoungleehanKorean/blob/a45be186a1c9aa8ebc7252bde0b215c31f6db9b5/client/src/pages/Cart.js#L20 

I love the way of naming booleans like above! That's great.
It may be described on airbnb style guide too. 
Everyone! please put name on boolean start with `is` `has` or something

**Comment by sweetrain05** [comment]
Nice to hear this!! We will keep it up!  :)
